### ISSUE TITLE
Evopy not producing optimal genotype

### ISSUE THREAD

**Issue by ThomasKluiters** [evopy/evopy#21]
When running the example:
```python
EvoPy(lambda x: pow(x, 2), 1).run()
```
I expect an output that is very close to 0.

However, the answer is equal to the worst genotype, I think this is caused by the following:
```python
if not self.maximize:
   best = population[0] if population[0].fitness > best.fitness else best
 else:
   best = population[0] if population[0].fitness < best.fitness else best
```

I think the if statement should be flipped.

Though, we can just ignore this if statement all together:

As `best` is part of population, population[0] will always yield the best individual, therefore we can safely assume that population[0] will always be the best.

**Comment by gandreadis** [comment]
Fixed in #22
