### ISSUE TITLE
Support setting a target fitness value for early stop

### ISSUE THREAD

**Issue by gandreadis** [evopy/evopy#6]

**Comment by jopenmolles** [comment]
I'm not sure whether this is all than useful for evolution strategies as we will always resample the population to get the offspring with a gaussian distribution.

**Comment by gandreadis** [comment]
Hmm yes, but we could support a target fitness value that, if reached (within epsilon), triggers a finish event. What do you think?

**Comment by jopenmolles** [comment]
That could be nice, but is mostly for the use case where you already know the optimum value. This could be useful for testing how effective the evolution strategies are for a certain problem (e.g. how "fast" they reach the optimum),

**Comment by gandreadis** [comment]
Indeed! Updating the title now to reflect this
